const studentData = [
    { id: 'student1', rollNumber: '001', name: 'Sandip Pathe', status: 'P' },
    { id: 'student2', rollNumber: '002', name: 'Karisma Pasupalak', status: 'A' },
    { id: 'student3', rollNumber: '003', name: 'Riya Sharma', status: 'P' },
    { id: 'student4', rollNumber: '004', name: 'Vikram Singh', status: 'A' },
    { id: 'student5', rollNumber: '005', name: 'Priya Patel', status: 'P' },
    { id: 'student6', rollNumber: '006', name: 'Aarav Mehta', status: 'A' },
    { id: 'student7', rollNumber: '007', name: 'Anaya Verma', status: 'P' },
    { id: 'student8', rollNumber: '008', name: 'Rahul Kapoor', status: 'A' },
    { id: 'student9', rollNumber: '009', name: 'Kavita Reddy', status: 'P' },
    { id: 'student10', rollNumber: '010', name: 'Rohan Desai', status: 'P' },
    { id: 'student11', rollNumber: '011', name: 'Sara Khan', status: 'A' },
    { id: 'student12', rollNumber: '012', name: 'Aditya Joshi', status: 'P' },
    { id: 'student13', rollNumber: '013', name: 'Tanvi Gupta', status: 'A' },
    { id: 'student14', rollNumber: '014', name: 'Arjun Malhotra', status: 'P' },
    { id: 'student15', rollNumber: '015', name: 'Neha Khanna', status: 'A' },
    { id: 'student16', rollNumber: '016', name: 'Aryan Singhania', status: 'P' },
    { id: 'student17', rollNumber: '017', name: 'Mira Shah', status: 'A' },
    { id: 'student18', rollNumber: '018', name: 'Rajeev Mehera', status: 'P' },
    { id: 'student19', rollNumber: '019', name: 'Kirti Kapoor', status: 'P' },
    { id: 'student20', rollNumber: '020', name: 'Sanjay Verma', status: 'A' },
    { id: 'student21', rollNumber: '021', name: 'Pooja Patel', status: 'P' },
    { id: 'student22', rollNumber: '022', name: 'Rahul Sharma', status: 'A' }
];
export default studentData;